# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_auto_20171229_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, default='default-img.gif', null=True, upload_to='img/'),
        ),
    ]
