# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.TextField(blank=True, default='Siswa', max_length=500),
        ),
    ]
