# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('hari', models.CharField(max_length=10)),
                ('kelas', models.ManyToManyField(related_name='mapel_kelas', to='kbm.Kelas')),
            ],
            options={
                'verbose_name': 'Mapel',
                'verbose_name_plural': 'Mapel',
            },
        ),
        migrations.CreateModel(
            name='NilaiMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('angka', models.IntegerField()),
                ('mapel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapel_nilai', to='kbm.Mapel')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_siswa', to='kbm.Kelas')),
                ('mapel', models.ManyToManyField(related_name='mapel_siswa', to='kbm.Mapel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.AddField(
            model_name='nilaimapel',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_nilai', to='kbm.Siswa'),
        ),
    ]
