# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('hari', models.CharField(max_length=50)),
                ('tahun_ajaran', models.CharField(max_length=4)),
                ('kelas', models.ManyToManyField(related_name='mapel_kelas', to='kbm.Kelas')),
            ],
            options={
                'verbose_name': 'Mapel',
                'verbose_name_plural': 'Mapel',
            },
        ),
        migrations.CreateModel(
            name='NilaiMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pengetahuan', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('keterampilan', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('semester', models.CharField(choices=[('smt1', 'SEMESTER 1'), ('smt2', 'SEMESTER 2')], default='SEMESTER 1', max_length=10)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapel_nilai', to='kbm.Mapel')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_nilai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
            },
        ),
    ]
