# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siswa',
            options={},
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='location',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='mapel',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='user',
        ),
    ]
