# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kbm', '0002_auto_20171114_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name_plural': 'Siswa'},
        ),
        migrations.AddField(
            model_name='siswa',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='siswa',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kelas_siswa', to='kbm.Kelas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siswa',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='siswa',
            name='mapel',
            field=models.ManyToManyField(related_name='mapel_siswa', to='kbm.Mapel'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siswa',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
