# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0003_auto_20171114_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
