# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0004_auto_20171114_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
