# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0005_auto_20171114_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='hari',
            field=models.CharField(max_length=50),
        ),
    ]
