# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0006_auto_20171114_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapel',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='nilaimapel',
            name='mapel',
        ),
        migrations.RemoveField(
            model_name='nilaimapel',
            name='siswa',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='mapel',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='user',
        ),
        migrations.DeleteModel(
            name='Kelas',
        ),
        migrations.DeleteModel(
            name='Mapel',
        ),
        migrations.DeleteModel(
            name='NilaiMapel',
        ),
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
