# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kbm', '0007_auto_20171230_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('hari', models.CharField(max_length=50)),
                ('kelas', models.ManyToManyField(related_name='mapel_kelas', to='kbm.Kelas')),
            ],
            options={
                'verbose_name': 'Mapel',
                'verbose_name_plural': 'Mapel',
            },
        ),
    ]
