# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kbm', '0008_kelas_mapel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('angka', models.IntegerField()),
                ('mapel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapel_nilai', to='kbm.Mapel')),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_nilai', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
            },
        ),
    ]
