# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0009_nilaimapel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilaimapel',
            name='angka',
        ),
        migrations.AddField(
            model_name='nilaimapel',
            name='keterampilan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='nilaimapel',
            name='pengetahuan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
