# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0010_auto_20180110_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilaimapel',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 2')], default='Semester 1', max_length=10),
        ),
    ]
