# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbm', '0012_auto_20180110_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimapel',
            name='semester',
            field=models.CharField(choices=[('smt1', 'SEMESTER 1'), ('smt2', 'SEMESTER 2')], default='SEMESTER 1', max_length=10),
        ),
    ]
